import {
  pgTable,
  uuid,
  text,
  integer,
  real,
  boolean,
  timestamp,
  index,
  unique,
} from "drizzle-orm/pg-core";
import { user } from "./auth-schema";

// ─── Activity Tokens ──────────────────────────────────────────────────────────
// API tokens generated by the user to authenticate the browser extension.
// The raw token is shown only once at creation time; only a SHA-256 hash is stored.
export const activityTokens = pgTable(
  "activity_tokens",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .references(() => user.id, { onDelete: "cascade" })
      .notNull(),
    name: text("name").notNull(), // friendly label, e.g. "Chrome extension"
    tokenHash: text("token_hash").notNull().unique(), // SHA-256(raw_token)
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => [
    index("idx_activity_tokens_user").on(table.userId),
    index("idx_activity_tokens_hash").on(table.tokenHash),
  ]
);

// ─── Current Activity ─────────────────────────────────────────────────────────
// Ephemeral "watching now" state — one row per user, upserted on each heartbeat.
// A cron job (or TTL-based query) clears stale rows older than ~5 minutes.
export const currentActivity = pgTable(
  "current_activity",
  {
    userId: uuid("user_id")
      .primaryKey()
      .references(() => user.id, { onDelete: "cascade" }),
    tmdbId: integer("tmdb_id"),          // TMDB id of the media (null for unresolved)
    mediaType: text("media_type"),        // "movie" | "episode"
    title: text("title").notNull(),       // raw title read from the DOM
    season: integer("season"),            // null for movies
    episode: integer("episode"),          // null for movies
    progress: real("progress"),           // 0–100 %
    source: text("source"),               // "netflix" | "prime" | "disney" | "youtube"
    status: text("status").notNull(),     // "watching" | "paused" | "finished"
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index("idx_current_activity_updated").on(table.updatedAt),
  ]
);

// ─── Scrobbles ────────────────────────────────────────────────────────────────
// Permanent, chronological watch history. Created automatically when progress
// reaches the configured threshold (~80 %), or manually by the user.
// Rewatches produce new rows — history is append-only.
export const scrobbles = pgTable(
  "scrobbles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .references(() => user.id, { onDelete: "cascade" })
      .notNull(),
    tmdbId: integer("tmdb_id"),           // TMDB id (null for manual scrobbles without lookup)
    mediaType: text("media_type").notNull(), // "movie" | "episode"
    title: text("title").notNull(),
    season: integer("season"),            // null for movies
    episode: integer("episode"),          // null for movies
    runtimeMinutes: integer("runtime_minutes"), // used to compute total watch time
    source: text("source").notNull(),     // "netflix" | "prime" | "disney" | "youtube" | "manual"
    progress: real("progress"),           // % when scrobble was triggered
    isManual: boolean("is_manual").default(false), // true = added via site UI
    watchedAt: timestamp("watched_at", { withTimezone: true }).notNull(), // moment of completion
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  },
  (table) => [
    index("idx_scrobbles_user").on(table.userId),
    index("idx_scrobbles_user_watched").on(table.userId, table.watchedAt),
    index("idx_scrobbles_tmdb").on(table.tmdbId),
    unique("unique_auto_scrobble").on(
      table.userId,
      table.tmdbId,
      table.mediaType,
      table.season,
      table.episode,
      table.watchedAt
    ),
  ]
);
